### ISSUE TITLE
Nice new  libcurl wrapper

### ISSUE THREAD

**Issue by qwertynat** [glhrmfrts/porter#1]
Hi I am wondering how one would go about streaming HTTP responses.

Basically i have a websevice where i request data and once requested and the curl object is opened i simply poll for the returned data on that socket in my event loop since the data never ends, it continues streaming. 

At a high level in c code i would do something like  to set up the socket for streaming read /writes
curl_easy_setopt(handle, CURLOPT_URL, "https://test.com")
curl_easy_setopt(handle, CURLOPT_CONNECT_ONLY, 1L)
curl_easy_perform(handle) 

then to read the streamed data i would call the following from my event loop 
curl_easy_recv(handle, buf, sizeof(buf), &nread)

then to write the streamed data i would call the following from my event loop 
curl_easy_send(handle, req_string, req_len, &nsent))

Is there a way to accomplish this within porter?

**Comment by glhrmfrts** [comment]
At the moment there's no methods for this. But you can grab the curl handle of any request by calling `request.curl_handle()` and then calling the curl functions with that handle. So your example would like this:

```cpp
auto request = porter::sync_request{ "https://test.com" };
curl_easy_setopt(request.curl_handle(), CURLOPT_CONNECT_ONLY, 1L);
request.perform();

// ... to read data
curl_easy_recv(request.curl_handle(), buf, sizeof(buf), &nread);

// ... to write data
curl_easy_send(request.curl_handle(), req_string, req_len, &nsent);
```

This was something real quick I wrote to use at work so it's far from fancy, if you want some wrapper methods for this feel free to send a PR or wait until I have some time available to work on it.

Thanks!

**Comment by qwertynat** [comment]
thanks! this basically worked as you described
